name: Test
on:
  push:
  pull_request:
  schedule:
    - cron:  '30 5 4 * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['2.7', '3.6', '3.8']
      fail-fast: false
    steps:
        - name: "Software Install - Ubuntu"
          if: ${{ matrix.os == 'ubuntu-latest' }}
          run: |
            sudo apt-get install -y \
              build-essential \
              ca-certificates \
              curl \
              git \
              gzip \
              libfftw3-dev \
              libhdf5-dev \
              libgdbm-dev \
              pkg-config
        - name: "Software Install - MacOS"
          if: ${{ matrix.os == 'macos-latest' }}
          run: |
            brew install \
              fftw \
              hdf5 \
              pkg-config
        - uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - uses: actions/checkout@v2
        - name: "Software Install - Python"
          run: |
            pip install \
              setuptools \
              numpy \
              matplotlib \
              scipy \
              h5py
            pip install \
              git+https://github.com/lwa-project/lsl.git
            pip install \
             pylint
        - name: Build
          run: |
            cd TBN/Calibration
            make
        - name: Test
          continue-on-error: ${{ matrix.python-version == '2.7' }}
          run: |
            cd tests
            python -m unittest discover
